-- Generated by Oracle SQL Developer Data Modeler 4.2.0.932
--   at:        2017-11-15 03:08:19 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE db_pinterest.tbl_blog (
    codigo_publicacion   NUMBER(*,0) NOT NULL,
    direccion            VARCHAR2(4000 BYTE),
    titulo               VARCHAR2(500 BYTE),
    descripcion          VARCHAR2(4000 BYTE),
    fecha                DATE,
    codigo_usuario       NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_blog_pk ON
    db_pinterest.tbl_blog ( codigo_publicacion ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_blog ADD CONSTRAINT tbl_blog_pk PRIMARY KEY ( codigo_publicacion )
    USING INDEX db_pinterest.tbl_blog_pk;

CREATE TABLE db_pinterest.tbl_categorias (
    codigo_categoria         NUMBER(*,0) NOT NULL,
    nombre_categoria         VARCHAR2(400 BYTE),
    codigo_categoria_padre   NUMBER(*,0),
    fecha_creacion           DATE,
    descripcion              VARCHAR2(4000 BYTE),
    codigo_usuario           NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_categorias_pk ON
    db_pinterest.tbl_categorias ( codigo_categoria ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_categorias ADD CONSTRAINT tbl_categorias_pk PRIMARY KEY ( codigo_categoria )
    USING INDEX db_pinterest.tbl_categorias_pk;

CREATE TABLE db_pinterest.tbl_chat_x_usuario (
    codigo_usuario           NUMBER(*,0) NOT NULL,
    codigo_usuario_destino   NUMBER(*,0) NOT NULL,
    codigo_mensaje           NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_chat_x_usuario_pk ON
    db_pinterest.tbl_chat_x_usuario (
        codigo_usuario
    ASC,
        codigo_usuario_destino
    ASC,
        codigo_mensaje
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_chat_x_usuario ADD CONSTRAINT tbl_chat_x_usuario_pk PRIMARY KEY ( codigo_usuario,codigo_usuario_destino,codigo_mensaje
 )
    USING INDEX db_pinterest.tbl_chat_x_usuario_pk;

CREATE TABLE db_pinterest.tbl_comentario (
    codigo_comentario   NUMBER(*,0) NOT NULL,
    codigo_usuario      NUMBER(*,0) NOT NULL,
    codigo_pines        NUMBER(*,0) NOT NULL,
    comentario          VARCHAR2(4000 BYTE),
    hora                DATE,
    fecha               DATE
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_comentario_pk ON
    db_pinterest.tbl_comentario ( codigo_comentario ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_comentario ADD CONSTRAINT tbl_comentario_pk PRIMARY KEY ( codigo_comentario )
    USING INDEX db_pinterest.tbl_comentario_pk;

CREATE TABLE db_pinterest.tbl_correo (
    codigo_correo   NUMBER(*,0) NOT NULL,
    texto_correo    VARCHAR2(4000 BYTE),
    fecha_correo    DATE,
    hora_correo     DATE
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.bandeja_pk ON
    db_pinterest.tbl_correo ( codigo_correo ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_correo ADD CONSTRAINT bandeja_pk PRIMARY KEY ( codigo_correo )
    USING INDEX db_pinterest.bandeja_pk;

CREATE TABLE db_pinterest.tbl_correo_x_usuario (
    codigo_usuario           NUMBER(*,0) NOT NULL,
    codigo_usuario_destino   NUMBER(*,0) NOT NULL,
    codigo_correo            NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_correo_x_usuario_pk ON
    db_pinterest.tbl_correo_x_usuario (
        codigo_usuario
    ASC,
        codigo_usuario_destino
    ASC,
        codigo_correo
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_correo_x_usuario ADD CONSTRAINT tbl_correo_x_usuario_pk PRIMARY KEY ( codigo_usuario,codigo_usuario_destino,codigo_correo
 )
    USING INDEX db_pinterest.tbl_correo_x_usuario_pk;

CREATE TABLE db_pinterest.tbl_detuncia_x_comentario (
    codigo_usuario      NUMBER(*,0) NOT NULL,
    codigo_comentario   NUMBER(*,0) NOT NULL,
    codigo_denuncia     NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_detuncia_x_comentario_pk ON
    db_pinterest.tbl_detuncia_x_comentario (
        codigo_usuario
    ASC,
        codigo_comentario
    ASC,
        codigo_denuncia
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_detuncia_x_comentario ADD CONSTRAINT tbl_detuncia_x_comentario_pk PRIMARY KEY ( codigo_usuario,codigo_comentario
,codigo_denuncia )
    USING INDEX db_pinterest.tbl_detuncia_x_comentario_pk;

CREATE TABLE db_pinterest.tbl_detuncia_x_pin (
    codigo_usuario    NUMBER(*,0) NOT NULL,
    codigo_pines      NUMBER(*,0) NOT NULL,
    codigo_denuncia   NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_detuncia_x_tablero_pk ON
    db_pinterest.tbl_detuncia_x_pin (
        codigo_denuncia
    ASC,
        codigo_pines
    ASC,
        codigo_usuario
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_detuncia_x_pin ADD CONSTRAINT tbl_detuncia_x_tablero_pk PRIMARY KEY ( codigo_denuncia,codigo_pines,codigo_usuario
 )
    USING INDEX db_pinterest.tbl_detuncia_x_tablero_pk;

CREATE TABLE db_pinterest.tbl_detuncia_x_tablero (
    codigo_usuario    NUMBER(*,0) NOT NULL,
    codigo_tablero    NUMBER(*,0) NOT NULL,
    codigo_denuncia   NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_detuncia_x_pin_pk ON
    db_pinterest.tbl_detuncia_x_tablero (
        codigo_denuncia
    ASC,
        codigo_tablero
    ASC,
        codigo_usuario
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_detuncia_x_tablero ADD CONSTRAINT tbl_detuncia_x_pin_pk PRIMARY KEY ( codigo_denuncia,codigo_tablero,codigo_usuario
 )
    USING INDEX db_pinterest.tbl_detuncia_x_pin_pk;

CREATE TABLE db_pinterest.tbl_detuncia_x_usuario (
    codigo_usuario              NUMBER(*,0) NOT NULL,
    codigo_usuario_denunciado   NUMBER(*,0) NOT NULL,
    codigo_denuncia             NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_detuncia_x_usuario_pk ON
    db_pinterest.tbl_detuncia_x_usuario (
        codigo_usuario
    ASC,
        codigo_usuario_denunciado
    ASC,
        codigo_denuncia
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_detuncia_x_usuario ADD CONSTRAINT tbl_detuncia_x_usuario_pk PRIMARY KEY ( codigo_usuario,codigo_usuario_denunciado
,codigo_denuncia )
    USING INDEX db_pinterest.tbl_detuncia_x_usuario_pk;

CREATE TABLE db_pinterest.tbl_empresa (
    codigo_empresa        NUMBER(*,0) NOT NULL,
    codigo_tipo_empresa   NUMBER(*,0) NOT NULL,
    sitio_web             VARCHAR2(4000 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_empresa_pk ON
    db_pinterest.tbl_empresa ( codigo_empresa ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_empresa ADD CONSTRAINT tbl_empresa_pk PRIMARY KEY ( codigo_empresa )
    USING INDEX db_pinterest.tbl_empresa_pk;

CREATE TABLE db_pinterest.tbl_fotos (
    codigo_foto   NUMBER(*,0) NOT NULL,
    foto          BLOB,
    alto          NUMBER(*,0),
    ancho         NUMBER(*,0),
    url_foto      VARCHAR2(300 BYTE),
    sitio_web     VARCHAR2(300 BYTE)
)
    TABLESPACE users LOGGING
    LOB ( foto ) STORE AS (
        TABLESPACE users
        STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
        CHUNK 8192
        RETENTION
        ENABLE STORAGE IN ROW
        NOCACHE LOGGING
    );

CREATE UNIQUE INDEX db_pinterest.tbl_fotos_pk ON
    db_pinterest.tbl_fotos ( codigo_foto ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_fotos ADD CONSTRAINT tbl_fotos_pk PRIMARY KEY ( codigo_foto )
    USING INDEX db_pinterest.tbl_fotos_pk;

CREATE TABLE db_pinterest.tbl_genero (
    codigo_genero   NUMBER(*,0) NOT NULL,
    tipo_genero     VARCHAR2(200 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_genero_pk ON
    db_pinterest.tbl_genero ( codigo_genero ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_genero ADD CONSTRAINT tbl_genero_pk PRIMARY KEY ( codigo_genero )
    USING INDEX db_pinterest.tbl_genero_pk;

CREATE TABLE db_pinterest.tbl_historial (
    codigo_historial   NUMBER(*,0) NOT NULL,
    nombre_busqueda    VARCHAR2(4000 BYTE),
    codigo_usuario     NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_historial_pk ON
    db_pinterest.tbl_historial ( codigo_historial ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_historial ADD CONSTRAINT tbl_historial_pk PRIMARY KEY ( codigo_historial )
    USING INDEX db_pinterest.tbl_historial_pk;

CREATE TABLE db_pinterest.tbl_idioma (
    codigo_idioma   NUMBER(*,0) NOT NULL,
    nombre_idioma   VARCHAR2(4000 BYTE),
    abreviatura     VARCHAR2(20 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_idioma_pk ON
    db_pinterest.tbl_idioma ( codigo_idioma ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_idioma ADD CONSTRAINT tbl_idioma_pk PRIMARY KEY ( codigo_idioma )
    USING INDEX db_pinterest.tbl_idioma_pk;

CREATE TABLE db_pinterest.tbl_lugar (
    codigo_lugar         NUMBER(*,0) NOT NULL,
    codigo_lugar_padre   NUMBER(*,0),
    nombre_lugar         VARCHAR2(4000 BYTE),
    latitud              NUMBER(*,0),
    longitud             NUMBER(*,0),
    iniciales            VARCHAR2(4000 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_lugar_pk ON
    db_pinterest.tbl_lugar ( codigo_lugar ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_lugar ADD CONSTRAINT tbl_lugar_pk PRIMARY KEY ( codigo_lugar )
    USING INDEX db_pinterest.tbl_lugar_pk;

CREATE TABLE db_pinterest.tbl_mensaje (
    codigo_mensaje   NUMBER(*,0) NOT NULL,
    mensaje          VARCHAR2(500 BYTE),
    fecha_mensaje    DATE,
    hora_mensaje     DATE
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_chat_pk ON
    db_pinterest.tbl_mensaje ( codigo_mensaje ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_mensaje ADD CONSTRAINT tbl_chat_pk PRIMARY KEY ( codigo_mensaje )
    USING INDEX db_pinterest.tbl_chat_pk;

CREATE TABLE db_pinterest.tbl_notifi_x_comentario (
    codigo_notificaciones   NUMBER(*,0) NOT NULL,
    codigo_comentario       NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE TABLE db_pinterest.tbl_notificacion (
    codigo_notificaciones      NUMBER(*,0) NOT NULL,
    codigo_usuario             NUMBER(*,0) NOT NULL,
    codigo_tipo_notificacion   NUMBER(*,0) NOT NULL,
    notificacion               VARCHAR2(4000 BYTE),
    fecha_notificacion         DATE,
    hora_notificacion          DATE
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_notificacion_pk ON
    db_pinterest.tbl_notificacion ( codigo_notificaciones ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_notificacion ADD CONSTRAINT tbl_notificacion_pk PRIMARY KEY ( codigo_notificaciones )
    USING INDEX db_pinterest.tbl_notificacion_pk;

CREATE TABLE db_pinterest.tbl_notificaciones_x_pines (
    codigo_notificaciones   NUMBER(*,0) NOT NULL,
    codigo_pines            NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE TABLE db_pinterest.tbl_notificaciones_x_tablero (
    codigo_notificaciones   NUMBER(*,0) NOT NULL,
    codigo_tablero          NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE TABLE db_pinterest.tbl_persona (
    codigo_persona     NUMBER(*,0) NOT NULL,
    apellido           VARCHAR2(4000 BYTE),
    fecha_nacimiento   DATE
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_persona_pk ON
    db_pinterest.tbl_persona ( codigo_persona ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_persona ADD CONSTRAINT tbl_persona_pk PRIMARY KEY ( codigo_persona )
    USING INDEX db_pinterest.tbl_persona_pk;

CREATE TABLE db_pinterest.tbl_pines (
    codigo_pines     NUMBER(*,0) NOT NULL,
    codigo_usuario   NUMBER(*,0) NOT NULL,
    codigo_tablero   NUMBER(*,0) NOT NULL,
    codigo_foto      NUMBER(*,0) NOT NULL,
    nombre_pin       VARCHAR2(4000 BYTE),
    direccion        VARCHAR2(4000 BYTE),
    descripcion      VARCHAR2(4000 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_pines_pk ON
    db_pinterest.tbl_pines ( codigo_pines ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_pines ADD CONSTRAINT tbl_pines_pk PRIMARY KEY ( codigo_pines )
    USING INDEX db_pinterest.tbl_pines_pk;

CREATE TABLE db_pinterest.tbl_redes_sociales (
    codigo_red_social   NUMBER(*,0) NOT NULL,
    nombre_red          VARCHAR2(4000 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_redes_sociales_pk ON
    db_pinterest.tbl_redes_sociales ( codigo_red_social ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_redes_sociales ADD CONSTRAINT tbl_redes_sociales_pk PRIMARY KEY ( codigo_red_social )
    USING INDEX db_pinterest.tbl_redes_sociales_pk;

CREATE TABLE db_pinterest.tbl_redes_x_usuario (
    codigo_persona      NUMBER(*,0) NOT NULL,
    codigo_red_social   NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE TABLE db_pinterest.tbl_seguidores_x_categoria (
    codigo_usuario     NUMBER(*,0) NOT NULL,
    codigo_categoria   NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE TABLE db_pinterest.tbl_seguidores_x_tableero (
    codigo_usuario   NUMBER(*,0) NOT NULL,
    codigo_tablero   NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_seguidores_x_tableero_pk ON
    db_pinterest.tbl_seguidores_x_tableero (
        codigo_usuario
    ASC,
        codigo_tablero
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_seguidores_x_tableero ADD CONSTRAINT tbl_seguidores_x_tableero_pk PRIMARY KEY ( codigo_usuario,codigo_tablero
 )
    USING INDEX db_pinterest.tbl_seguidores_x_tableero_pk;

CREATE TABLE db_pinterest.tbl_seguidores_x_usuario (
    codigo_usuario    NUMBER(*,0) NOT NULL,
    codigo_seguidor   NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE TABLE db_pinterest.tbl_tablero (
    codigo_tablero        NUMBER(*,0) NOT NULL,
    codigo_usuario        NUMBER(*,0) NOT NULL,
    codigo_tipo_tablero   NUMBER(*,0) NOT NULL,
    nombre_tablero        VARCHAR2(400 BYTE),
    descripcion           VARCHAR2(4000 BYTE),
    fecha_creacion        DATE
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_tablero_pk ON
    db_pinterest.tbl_tablero ( codigo_tablero ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_tablero ADD CONSTRAINT tbl_tablero_pk PRIMARY KEY ( codigo_tablero )
    USING INDEX db_pinterest.tbl_tablero_pk;

CREATE TABLE db_pinterest.tbl_tablero_x_categoria (
    codigo_categoria   NUMBER(*,0) NOT NULL,
    codigo_tablero     NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE TABLE db_pinterest.tbl_tablero_x_usuario (
    codigo_usuario   NUMBER(*,0) NOT NULL,
    codigo_tablero   NUMBER(*,0) NOT NULL
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_tablero_x_usuario_pk ON
    db_pinterest.tbl_tablero_x_usuario (
        codigo_usuario
    ASC,
        codigo_tablero
    ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_tablero_x_usuario ADD CONSTRAINT tbl_tablero_x_usuario_pk PRIMARY KEY ( codigo_usuario,codigo_tablero )
    USING INDEX db_pinterest.tbl_tablero_x_usuario_pk;

CREATE TABLE db_pinterest.tbl_tipo_denuncia (
    codigo_denuncia   NUMBER(*,0) NOT NULL,
    nombre_denuncia   VARCHAR2(1000 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_tipo_denuncia_pk ON
    db_pinterest.tbl_tipo_denuncia ( codigo_denuncia ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_tipo_denuncia ADD CONSTRAINT tbl_tipo_denuncia_pk PRIMARY KEY ( codigo_denuncia )
    USING INDEX db_pinterest.tbl_tipo_denuncia_pk;

CREATE TABLE db_pinterest.tbl_tipo_empresa (
    codigo_tipo_empresa   NUMBER(*,0) NOT NULL,
    nombre_tipo           VARCHAR2(4000 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_tipo_empresa_pk ON
    db_pinterest.tbl_tipo_empresa ( codigo_tipo_empresa ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_tipo_empresa ADD CONSTRAINT tbl_tipo_empresa_pk PRIMARY KEY ( codigo_tipo_empresa )
    USING INDEX db_pinterest.tbl_tipo_empresa_pk;

CREATE TABLE db_pinterest.tbl_tipo_notificacion (
    codigo_tipo_notificacion   NUMBER(*,0) NOT NULL,
    tipo_notificacion          VARCHAR2(4000 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_tipo_notificacion_pk ON
    db_pinterest.tbl_tipo_notificacion ( codigo_tipo_notificacion ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_tipo_notificacion ADD CONSTRAINT tbl_tipo_notificacion_pk PRIMARY KEY ( codigo_tipo_notificacion )
    USING INDEX db_pinterest.tbl_tipo_notificacion_pk;

CREATE TABLE db_pinterest.tbl_tipo_tablero (
    codigo_tipo_tablero   NUMBER(*,0) NOT NULL,
    nombre_tipo_tablero   VARCHAR2(400 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_tipo_tablero_pk ON
    db_pinterest.tbl_tipo_tablero ( codigo_tipo_tablero ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_tipo_tablero ADD CONSTRAINT tbl_tipo_tablero_pk PRIMARY KEY ( codigo_tipo_tablero )
    USING INDEX db_pinterest.tbl_tipo_tablero_pk;

CREATE TABLE db_pinterest.tbl_tipo_usuario (
    codigo_tipo_usuario   NUMBER(*,0) NOT NULL,
    nombre_tipo           VARCHAR2(200 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_tipo_usuario_pk ON
    db_pinterest.tbl_tipo_usuario ( codigo_tipo_usuario ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_tipo_usuario ADD CONSTRAINT tbl_tipo_usuario_pk PRIMARY KEY ( codigo_tipo_usuario )
    USING INDEX db_pinterest.tbl_tipo_usuario_pk;

CREATE TABLE db_pinterest.tbl_usuario (
    codigo_usuario        NUMBER(*,0) NOT NULL,
    codigo_lugar          NUMBER(*,0) NOT NULL,
    codigo_tipo_usuario   NUMBER(*,0) NOT NULL,
    codigo_genero         NUMBER(*,0) NOT NULL,
    codigo_foto           NUMBER(*,0) NOT NULL,
    codigo_idioma         NUMBER(*,0) NOT NULL,
    alias                 VARCHAR2(200 BYTE),
    nombre                VARCHAR2(200 BYTE),
    contrasenia           VARCHAR2(100 BYTE),
    correo                VARCHAR2(200 BYTE),
    telefono              VARCHAR2(200 BYTE)
)
    TABLESPACE users LOGGING;

CREATE UNIQUE INDEX db_pinterest.tbl_usuario_pk ON
    db_pinterest.tbl_usuario ( codigo_usuario ASC )
        TABLESPACE users LOGGING;

ALTER TABLE db_pinterest.tbl_usuario ADD CONSTRAINT tbl_usuario_pk PRIMARY KEY ( codigo_usuario )
    USING INDEX db_pinterest.tbl_usuario_pk;

ALTER TABLE db_pinterest.tbl_blog ADD CONSTRAINT tbl_blo_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_categorias ADD CONSTRAINT " TBL_CAT_FK" FOREIGN KEY ( codigo_categoria_padre )
    REFERENCES db_pinterest.tbl_categorias ( codigo_categoria )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_categorias ADD CONSTRAINT "TBL_CAT _TBL_USU_FK" FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_chat_x_usuario ADD CONSTRAINT "TBL_CHA_X_USU _TBL_CHA" FOREIGN KEY ( codigo_mensaje )
    REFERENCES db_pinterest.tbl_mensaje ( codigo_mensaje )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_chat_x_usuario ADD CONSTRAINT tbl_cha_x_usu_tbl_usu FOREIGN KEY ( codigo_usuario_destino )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_chat_x_usuario ADD CONSTRAINT tbl_cha_x_usu_tbl_usuv2 FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_comentario ADD CONSTRAINT "TBL_COM _TBL_PIN _FK" FOREIGN KEY ( codigo_pines )
    REFERENCES db_pinterest.tbl_pines ( codigo_pines )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_comentario ADD CONSTRAINT "TBL_COM _TBL_USU_FK" FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_correo_x_usuario ADD CONSTRAINT tbl_cor_x_usu_tbl_cor FOREIGN KEY ( codigo_correo )
    REFERENCES db_pinterest.tbl_correo ( codigo_correo )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_correo_x_usuario ADD CONSTRAINT tbl_cor_x_usu_tbl_usu FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_correo_x_usuario ADD CONSTRAINT tbl_cor_x_usu_usu FOREIGN KEY ( codigo_usuario_destino )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_tablero ADD CONSTRAINT "TBL_DE_X_PIN_TBL_TAB _FK" FOREIGN KEY ( codigo_tablero )
    REFERENCES db_pinterest.tbl_tablero ( codigo_tablero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_comentario ADD CONSTRAINT tbl_den_x_com_tbl_usu FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_comentario ADD CONSTRAINT tbl_den_x_com_tip_den FOREIGN KEY ( codigo_denuncia )
    REFERENCES db_pinterest.tbl_tipo_denuncia ( codigo_denuncia )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_tablero ADD CONSTRAINT tbl_den_x_pin_tip_den FOREIGN KEY ( codigo_denuncia )
    REFERENCES db_pinterest.tbl_tipo_denuncia ( codigo_denuncia )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_tablero ADD CONSTRAINT tbl_den_x_pin_usu FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_pin ADD CONSTRAINT tbl_den_x_tab_pin FOREIGN KEY ( codigo_pines )
    REFERENCES db_pinterest.tbl_pines ( codigo_pines )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_pin ADD CONSTRAINT tbl_den_x_tab_tip_den FOREIGN KEY ( codigo_denuncia )
    REFERENCES db_pinterest.tbl_tipo_denuncia ( codigo_denuncia )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_pin ADD CONSTRAINT tbl_den_x_usu FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_usuario ADD CONSTRAINT tbl_den_x_usu_tbl_usu FOREIGN KEY ( codigo_usuario_denunciado )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_usuario ADD CONSTRAINT tbl_den_x_usu_tip_den FOREIGN KEY ( codigo_denuncia )
    REFERENCES db_pinterest.tbl_tipo_denuncia ( codigo_denuncia )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_usuario ADD CONSTRAINT tbl_den_x_usu_usu_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_detuncia_x_comentario ADD CONSTRAINT tbl_det_x_com_tbl_com FOREIGN KEY ( codigo_comentario )
    REFERENCES db_pinterest.tbl_comentario ( codigo_comentario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_empresa ADD CONSTRAINT tbl_emp_tbl_tip_emp FOREIGN KEY ( codigo_tipo_empresa )
    REFERENCES db_pinterest.tbl_tipo_empresa ( codigo_tipo_empresa )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_empresa ADD CONSTRAINT tbl_emp_tbl_usu FOREIGN KEY ( codigo_empresa )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_historial ADD CONSTRAINT tbl_his_tbl_usu FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_lugar ADD CONSTRAINT tbl_lug_lug FOREIGN KEY ( codigo_lugar_padre )
    REFERENCES db_pinterest.tbl_lugar ( codigo_lugar )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notifi_x_comentario ADD CONSTRAINT tbl_not_com_tbl_com FOREIGN KEY ( codigo_comentario )
    REFERENCES db_pinterest.tbl_comentario ( codigo_comentario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notificaciones_x_pines ADD CONSTRAINT "TBL_NOT_PIN _FK" FOREIGN KEY ( codigo_pines )
    REFERENCES db_pinterest.tbl_pines ( codigo_pines )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notificaciones_x_pines ADD CONSTRAINT tbl_not_pin_tbl_not_fk FOREIGN KEY ( codigo_notificaciones )
    REFERENCES db_pinterest.tbl_notificacion ( codigo_notificaciones )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notificacion ADD CONSTRAINT tbl_not_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notificacion ADD CONSTRAINT tbl_not_tip_not FOREIGN KEY ( codigo_tipo_notificacion )
    REFERENCES db_pinterest.tbl_tipo_notificacion ( codigo_tipo_notificacion )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notifi_x_comentario ADD CONSTRAINT tbl_not_x_com_not_fk FOREIGN KEY ( codigo_notificaciones )
    REFERENCES db_pinterest.tbl_notificacion ( codigo_notificaciones )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notificaciones_x_tablero ADD CONSTRAINT tbl_not_x_tab_not_fk FOREIGN KEY ( codigo_notificaciones )
    REFERENCES db_pinterest.tbl_notificacion ( codigo_notificaciones )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_notificaciones_x_tablero ADD CONSTRAINT "TBL_NOTL_TAB _FK" FOREIGN KEY ( codigo_tablero )
    REFERENCES db_pinterest.tbl_tablero ( codigo_tablero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_persona ADD CONSTRAINT "TBL_PER _TBL_USU" FOREIGN KEY ( codigo_persona )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_pines ADD CONSTRAINT "TBL_PIN _TBL_FOT_FK" FOREIGN KEY ( codigo_foto )
    REFERENCES db_pinterest.tbl_fotos ( codigo_foto )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_pines ADD CONSTRAINT "TBL_PIN _TBL_TAB _FK" FOREIGN KEY ( codigo_tablero )
    REFERENCES db_pinterest.tbl_tablero ( codigo_tablero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_pines ADD CONSTRAINT "TBL_PIN _TBL_USU_FK" FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_redes_x_usuario ADD CONSTRAINT tbl_red_x_usu_per_fk FOREIGN KEY ( codigo_persona )
    REFERENCES db_pinterest.tbl_persona ( codigo_persona )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_redes_x_usuario ADD CONSTRAINT tbl_red_x_usu_soc FOREIGN KEY ( codigo_red_social )
    REFERENCES db_pinterest.tbl_redes_sociales ( codigo_red_social )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_seguidores_x_categoria ADD CONSTRAINT tbl_seg_cat_tbl_usu FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_seguidores_x_tableero ADD CONSTRAINT "TBL_SEG_TAB _FK" FOREIGN KEY ( codigo_tablero )
    REFERENCES db_pinterest.tbl_tablero ( codigo_tablero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_seguidores_x_usuario ADD CONSTRAINT tbl_seg_usu_tbl_usu FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_seguidores_x_categoria ADD CONSTRAINT tbl_seg_x_cat_cat FOREIGN KEY ( codigo_categoria )
    REFERENCES db_pinterest.tbl_categorias ( codigo_categoria )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_seguidores_x_tableero ADD CONSTRAINT tbl_seg_x_tab_usu_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_seguidores_x_usuario ADD CONSTRAINT tbl_seg_x_usu_usu FOREIGN KEY ( codigo_seguidor )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_tablero ADD CONSTRAINT "TBL_TAB_TIP_TAB _FK" FOREIGN KEY ( codigo_tipo_tablero )
    REFERENCES db_pinterest.tbl_tipo_tablero ( codigo_tipo_tablero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_tablero ADD CONSTRAINT tbl_tab_usu_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_tablero_x_categoria ADD CONSTRAINT tbl_tab_x_cat FOREIGN KEY ( codigo_categoria )
    REFERENCES db_pinterest.tbl_categorias ( codigo_categoria )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_tablero_x_categoria ADD CONSTRAINT "TBL_TAB_X_CAT_TAB _FK" FOREIGN KEY ( codigo_tablero )
    REFERENCES db_pinterest.tbl_tablero ( codigo_tablero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_tablero_x_usuario ADD CONSTRAINT tbl_tab_x_usu_usu_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES db_pinterest.tbl_usuario ( codigo_usuario )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_usuario ADD CONSTRAINT tbl_usu_fot_fk FOREIGN KEY ( codigo_foto )
    REFERENCES db_pinterest.tbl_fotos ( codigo_foto )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_usuario ADD CONSTRAINT "TBL_USU_GEN _FK" FOREIGN KEY ( codigo_genero )
    REFERENCES db_pinterest.tbl_genero ( codigo_genero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_usuario ADD CONSTRAINT tbl_usu_idi_fk FOREIGN KEY ( codigo_idioma )
    REFERENCES db_pinterest.tbl_idioma ( codigo_idioma )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_usuario ADD CONSTRAINT tbl_usu_lug_fk FOREIGN KEY ( codigo_lugar )
    REFERENCES db_pinterest.tbl_lugar ( codigo_lugar )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_tablero_x_usuario ADD CONSTRAINT "TBL_USU_TAB _FK" FOREIGN KEY ( codigo_tablero )
    REFERENCES db_pinterest.tbl_tablero ( codigo_tablero )
NOT DEFERRABLE;

ALTER TABLE db_pinterest.tbl_usuario ADD CONSTRAINT "TBL_USU_TIP_USU _FK" FOREIGN KEY ( codigo_tipo_usuario )
    REFERENCES db_pinterest.tbl_tipo_usuario ( codigo_tipo_usuario )
NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            37
-- CREATE INDEX                            30
-- ALTER TABLE                             88
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
