--------------------------------------------------------
--  File created - Wednesday-November-15-2017   
--------------------------------------------------------
REM INSERTING into DB_PINTEREST.TBL_PINES
SET DEFINE OFF;
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (18,3,1,9,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (1,1,2,131,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (2,1,2,3,'JOSE','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (3,2,2,125,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (4,2,1,145,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (5,2,1,5,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (6,1,3,7,'IRIS','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (7,3,3,9,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (8,3,2,6,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (9,3,3,10,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (10,2,2,11,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (11,2,1,15,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (12,2,1,19,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (13,1,3,20,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (14,1,3,22,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (15,3,2,24,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (16,2,1,30,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (17,3,1,9,'maria','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (19,3,2,11,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (20,3,2,2,'JOSE','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (21,3,2,10,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (23,3,1,4,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (24,3,1,4,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (25,2,2,24,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (26,2,3,11,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (27,3,2,126,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (125,1,2,130,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (28,1,2,145,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (22,3,1,10,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (29,1,3,15,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (30,1,1,15,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (31,1,2,15,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (32,1,1,15,'MARIA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (33,1,1,11,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (34,1,3,11,'DEPORTES','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (35,1,2,5,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (36,1,3,5,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (37,1,1,5,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (38,1,1,5,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (39,1,3,5,'ANA','sdfga','sdfga');
Insert into DB_PINTEREST.TBL_PINES (CODIGO_PINES,CODIGO_USUARIO,CODIGO_TABLERO,CODIGO_FOTO,NOMBRE_PIN,DIRECCION,DESCRIPCION) values (40,1,3,145,'ANA','sdfga','sdfga');
