--------------------------------------------------------
--  File created - Wednesday-November-15-2017   
--------------------------------------------------------
REM INSERTING into DB_PINTEREST.TBL_TABLERO
SET DEFINE OFF;
Insert into DB_PINTEREST.TBL_TABLERO (CODIGO_TABLERO,CODIGO_USUARIO,CODIGO_TIPO_TABLERO,NOMBRE_TABLERO,DESCRIPCION,FECHA_CREACION) values (4,3,2,'MODA','SANDALIAS',to_date('07-NOV-17','DD-MON-RR'));
Insert into DB_PINTEREST.TBL_TABLERO (CODIGO_TABLERO,CODIGO_USUARIO,CODIGO_TIPO_TABLERO,NOMBRE_TABLERO,DESCRIPCION,FECHA_CREACION) values (1,1,1,'ANA','VESTIDOS',to_date('16-NOV-17','DD-MON-RR'));
Insert into DB_PINTEREST.TBL_TABLERO (CODIGO_TABLERO,CODIGO_USUARIO,CODIGO_TIPO_TABLERO,NOMBRE_TABLERO,DESCRIPCION,FECHA_CREACION) values (2,2,2,'JOSE','FALDAS',to_date('16-NOV-17','DD-MON-RR'));
Insert into DB_PINTEREST.TBL_TABLERO (CODIGO_TABLERO,CODIGO_USUARIO,CODIGO_TIPO_TABLERO,NOMBRE_TABLERO,DESCRIPCION,FECHA_CREACION) values (3,2,1,'DEPORTES','PELOTA',to_date('07-NOV-17','DD-MON-RR'));
