--------------------------------------------------------
--  File created - Wednesday-November-15-2017   
--------------------------------------------------------
REM INSERTING into DB_PINTEREST.TBL_COMENTARIO
SET DEFINE OFF;
Insert into DB_PINTEREST.TBL_COMENTARIO (CODIGO_COMENTARIO,CODIGO_USUARIO,CODIGO_PINES,COMENTARIO,HORA,FECHA) values (1,1,1,'ESTO ES UN COMENTARIO',null,null);
Insert into DB_PINTEREST.TBL_COMENTARIO (CODIGO_COMENTARIO,CODIGO_USUARIO,CODIGO_PINES,COMENTARIO,HORA,FECHA) values (2,1,2,'ESTO ES UN COMENTARIO',null,null);
Insert into DB_PINTEREST.TBL_COMENTARIO (CODIGO_COMENTARIO,CODIGO_USUARIO,CODIGO_PINES,COMENTARIO,HORA,FECHA) values (3,1,3,'ESTO ES UN COMENTARIO',null,null);
Insert into DB_PINTEREST.TBL_COMENTARIO (CODIGO_COMENTARIO,CODIGO_USUARIO,CODIGO_PINES,COMENTARIO,HORA,FECHA) values (4,2,10,'ESTO ES UN COMENTARIO',null,null);
Insert into DB_PINTEREST.TBL_COMENTARIO (CODIGO_COMENTARIO,CODIGO_USUARIO,CODIGO_PINES,COMENTARIO,HORA,FECHA) values (5,2,10,'ESTO ES UN COMENTARIO',null,null);
Insert into DB_PINTEREST.TBL_COMENTARIO (CODIGO_COMENTARIO,CODIGO_USUARIO,CODIGO_PINES,COMENTARIO,HORA,FECHA) values (6,3,6,'ESTO ES UN COMENTARIO',null,null);
