--------------------------------------------------------
--  File created - Wednesday-November-15-2017   
--------------------------------------------------------
REM INSERTING into DB_PINTEREST.TBL_TABLERO_X_USUARIO
SET DEFINE OFF;
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (1,1);
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (1,2);
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (1,3);
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (2,1);
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (2,2);
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (2,3);
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (3,1);
Insert into DB_PINTEREST.TBL_TABLERO_X_USUARIO (CODIGO_USUARIO,CODIGO_TABLERO) values (3,2);
