--------------------------------------------------------
--  File created - Monday-September-25-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_BLOG
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_BLOG" 
   (	"CODIGO_PUBLICACION" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(4000 BYTE), 
	"TITULO" VARCHAR2(500 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"FECHA" DATE, 
	"CODIGO_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CATEGORIAS 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_CATEGORIAS " 
   (	"CODIGO_CATEGORIA " NUMBER(*,0), 
	"NOMBRE_CATEGORIA " VARCHAR2(400 BYTE), 
	"CODIGO_CATEGORIA_PADRE" NUMBER(*,0), 
	"FECHA_CREACION" DATE, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"CODIGO_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CHAT_X_USUARIO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_USUARIO_DESTINO" NUMBER(*,0), 
	"CODIGO_MENSAJE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_COMENTARIO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_COMENTARIO " 
   (	"CODIGO_COMENTARIO " NUMBER(*,0), 
	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_PINES " NUMBER(*,0), 
	"COMENTARIO " VARCHAR2(4000 BYTE), 
	"HORA " DATE, 
	"FECHA " DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CORREO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_CORREO" 
   (	"CODIGO_CORREO" NUMBER(*,0), 
	"TEXTO_CORREO" VARCHAR2(4000 BYTE), 
	"FECHA_CORREO" DATE, 
	"HORA_CORREO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CORREO_X_USUARIO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_USUARIO_DESTINO" NUMBER(*,0), 
	"CODIGO_CORREO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DETUNCIA_X_COMENTARIO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_COMENTARIO " NUMBER(*,0), 
	"CODIGO_DENUNCIA " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DETUNCIA_X_PIN
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_PINES " NUMBER(*,0), 
	"CODIGO_DENUNCIA " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DETUNCIA_X_TABLERO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_TABLERO " NUMBER(*,0), 
	"CODIGO_DENUNCIA " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DETUNCIA_X_USUARIO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_USUARIO_DENUNCIADO" NUMBER(*,0), 
	"CODIGO_DENUNCIA " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_EMPRESA
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_EMPRESA" 
   (	"CODIGO_EMPRESA" NUMBER(*,0), 
	"CODIGO_TIPO_EMPRESA " NUMBER(*,0), 
	"SITIO_WEB" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_FOTOS
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_FOTOS" 
   (	"CODIGO_FOTO" NUMBER(*,0), 
	"FOTO" BLOB, 
	"ALTO" NUMBER(*,0), 
	"ANCHO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FOTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TBL_GENERO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_GENERO " 
   (	"CODIGO_GENERO " NUMBER(*,0), 
	"TIPO_GENERO " VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_HISTORIAL
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_HISTORIAL" 
   (	"CODIGO_HISTORIAL" NUMBER(*,0), 
	"NOMBRE_BUSQUEDA" VARCHAR2(4000 BYTE), 
	"CODIGO_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_IDIOMA
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_IDIOMA" 
   (	"CODIGO_IDIOMA" NUMBER(*,0), 
	"NOMBRE_IDIOMA" VARCHAR2(4000 BYTE), 
	"ABREVIATURA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_LUGAR 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_LUGAR " 
   (	"CODIGO_LUGAR " NUMBER(*,0), 
	"CODIGO_LUGAR_PADRE" NUMBER(*,0), 
	"NOMBRE_LUGAR " VARCHAR2(4000 BYTE), 
	"LATITUD " NUMBER(*,0), 
	"LONGITUD " NUMBER(*,0), 
	"INICIALES " VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_MENSAJE
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_MENSAJE" 
   (	"CODIGO_MENSAJE" NUMBER(*,0), 
	"MENSAJE " VARCHAR2(500 BYTE), 
	"FECHA_MENSAJE" DATE, 
	"HORA_MENSAJE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_NOTIFICACION
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_NOTIFICACION" 
   (	"CODIGO_NOTIFICACIONES " NUMBER(*,0), 
	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_TIPO_NOTIFICACION " NUMBER(*,0), 
	"NOTIFICACION " VARCHAR2(4000 BYTE), 
	"FECHA_NOTIFICACION " DATE, 
	"HORA_NOTIFICACION " DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_NOTIFICACIONES_X_PINES
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_PINES" 
   (	"CODIGO_NOTIFICACIONES " NUMBER(*,0), 
	"CODIGO_PINES " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_NOTIFICACIONES_X_TABLERO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_TABLERO" 
   (	"CODIGO_NOTIFICACIONES " NUMBER(*,0), 
	"CODIGO_TABLERO " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_NOTIFI_X_COMENTARIO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_NOTIFI_X_COMENTARIO" 
   (	"CODIGO_NOTIFICACIONES " NUMBER(*,0), 
	"CODIGO_COMENTARIO " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PERSONA 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_PERSONA " 
   (	"CODIGO_PERSONA" NUMBER(*,0), 
	"APELLIDO " VARCHAR2(4000 BYTE), 
	"FECHA_NACIMIENTO " DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PINES 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_PINES " 
   (	"CODIGO_PINES " NUMBER(*,0), 
	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_TABLERO " NUMBER(*,0), 
	"CODIGO_FOTO" NUMBER(*,0), 
	"NOMBRE_PIN " VARCHAR2(4000 BYTE), 
	"DIRECCION " VARCHAR2(4000 BYTE), 
	"DESCRIPCION " VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_REDES_SOCIALES 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_REDES_SOCIALES " 
   (	"CODIGO_RED_SOCIAL " NUMBER(*,0), 
	"NOMBRE_RED " VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_REDES_X_USUARIO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_REDES_X_USUARIO" 
   (	"CODIGO_PERSONA" NUMBER(*,0), 
	"CODIGO_RED_SOCIAL " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SEGUIDORES_X_CATEGORIA 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_CATEGORIA " 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_CATEGORIA " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SEGUIDORES_X_TABLEERO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO " 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_TABLERO " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SEGUIDORES_X_USUARIO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_USUARIO " 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_SEGUIDOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TABLERO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TABLERO " 
   (	"CODIGO_TABLERO " NUMBER(*,0), 
	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_TIPO_TABLERO " NUMBER(*,0), 
	"NOMBRE_TABLERO " VARCHAR2(400 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TABLERO_X_CATEGORIA 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TABLERO_X_CATEGORIA " 
   (	"CODIGO_CATEGORIA " NUMBER(*,0), 
	"CODIGO_TABLERO " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TABLERO_X_USUARIO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TABLERO_X_USUARIO " 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_TABLERO " NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_DENUNCIA 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TIPO_DENUNCIA " 
   (	"CODIGO_DENUNCIA " NUMBER(*,0), 
	"NOMBRE_DENUNCIA" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_EMPRESA 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TIPO_EMPRESA " 
   (	"CODIGO_TIPO_EMPRESA " NUMBER(*,0), 
	"NOMBRE TIPO " VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_NOTIFICACION 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TIPO_NOTIFICACION " 
   (	"CODIGO_TIPO_NOTIFICACION " NUMBER(*,0), 
	"TIPO_NOTIFICACION " VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_TABLERO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TIPO_TABLERO " 
   (	"CODIGO_TIPO_TABLERO " NUMBER(*,0), 
	"NOMBRE_TIPO_TABLERO " VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_USUARIO 
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_TIPO_USUARIO " 
   (	"CODIGO_TIPO_USUARIO " NUMBER(*,0), 
	"NOMBRE TIPO " VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIO
--------------------------------------------------------

  CREATE TABLE "DB_PINTEREST"."TBL_USUARIO" 
   (	"CODIGO_USUARIO" NUMBER(*,0), 
	"CODIGO_LUGAR " NUMBER(*,0), 
	"CODIGO_TIPO_USUARIO " NUMBER(*,0), 
	"CODIGO_GENERO " NUMBER(*,0), 
	"CODIGO_FOTO" NUMBER(*,0), 
	"CODIGO_IDIOMA" NUMBER(*,0), 
	"ALIAS " VARCHAR2(200 BYTE), 
	"NOMBRE " VARCHAR2(200 BYTE), 
	"CONTRASENIA " VARCHAR2(100 BYTE), 
	"CORREO " VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DB_PINTEREST.TBL_BLOG
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_CATEGORIAS "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_CHAT_X_USUARIO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_COMENTARIO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_CORREO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_CORREO_X_USUARIO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_DETUNCIA_X_COMENTARIO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_DETUNCIA_X_PIN
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_DETUNCIA_X_TABLERO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_DETUNCIA_X_USUARIO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_EMPRESA
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_FOTOS
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_GENERO "
SET DEFINE OFF;
Insert into DB_PINTEREST."TBL_GENERO " ("CODIGO_GENERO ","TIPO_GENERO ") values (1,'Masculino');
Insert into DB_PINTEREST."TBL_GENERO " ("CODIGO_GENERO ","TIPO_GENERO ") values (2,'Femenino');
REM INSERTING into DB_PINTEREST.TBL_HISTORIAL
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_IDIOMA
SET DEFINE OFF;
Insert into DB_PINTEREST.TBL_IDIOMA (CODIGO_IDIOMA,NOMBRE_IDIOMA,ABREVIATURA) values (1,'Español','ES');
Insert into DB_PINTEREST.TBL_IDIOMA (CODIGO_IDIOMA,NOMBRE_IDIOMA,ABREVIATURA) values (2,'Ingles','IN');
Insert into DB_PINTEREST.TBL_IDIOMA (CODIGO_IDIOMA,NOMBRE_IDIOMA,ABREVIATURA) values (3,'Frances','RF');
Insert into DB_PINTEREST.TBL_IDIOMA (CODIGO_IDIOMA,NOMBRE_IDIOMA,ABREVIATURA) values (4,'Italiano','IT');
Insert into DB_PINTEREST.TBL_IDIOMA (CODIGO_IDIOMA,NOMBRE_IDIOMA,ABREVIATURA) values (5,'Aleman','AL');
REM INSERTING into DB_PINTEREST."TBL_LUGAR "
SET DEFINE OFF;
Insert into DB_PINTEREST."TBL_LUGAR " ("CODIGO_LUGAR ",CODIGO_LUGAR_PADRE,"NOMBRE_LUGAR ","LATITUD ","LONGITUD ","INICIALES ") values (1,null,'Honduras',15,-87,'HON');
Insert into DB_PINTEREST."TBL_LUGAR " ("CODIGO_LUGAR ",CODIGO_LUGAR_PADRE,"NOMBRE_LUGAR ","LATITUD ","LONGITUD ","INICIALES ") values (2,1,'Franscisco Morazán',14,-87,'FRA_MZN');
Insert into DB_PINTEREST."TBL_LUGAR " ("CODIGO_LUGAR ",CODIGO_LUGAR_PADRE,"NOMBRE_LUGAR ","LATITUD ","LONGITUD ","INICIALES ") values (3,2,'Tegucigalpa',14,-87,'TEG');
REM INSERTING into DB_PINTEREST.TBL_MENSAJE
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_NOTIFICACION
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_NOTIFICACIONES_X_PINES
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_NOTIFICACIONES_X_TABLERO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_NOTIFI_X_COMENTARIO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_PERSONA "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_PINES "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_REDES_SOCIALES "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_REDES_X_USUARIO
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_SEGUIDORES_X_CATEGORIA "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_SEGUIDORES_X_TABLEERO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_SEGUIDORES_X_USUARIO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TABLERO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TABLERO_X_CATEGORIA "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TABLERO_X_USUARIO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TIPO_DENUNCIA "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TIPO_EMPRESA "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TIPO_NOTIFICACION "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TIPO_TABLERO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST."TBL_TIPO_USUARIO "
SET DEFINE OFF;
REM INSERTING into DB_PINTEREST.TBL_USUARIO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TBL_TABLERO_X_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_TABLERO_X_USUARIO_PK" ON "DB_PINTEREST"."TBL_TABLERO_X_USUARIO " ("CODIGO_USUARIO", "CODIGO_TABLERO ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_USUARIO_PK" ON "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_PERSONA_PK" ON "DB_PINTEREST"."TBL_PERSONA " ("CODIGO_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_NOTIFICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_NOTIFICACION_PK" ON "DB_PINTEREST"."TBL_NOTIFICACION" ("CODIGO_NOTIFICACIONES ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_FOTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_FOTOS_PK" ON "DB_PINTEREST"."TBL_FOTOS" ("CODIGO_FOTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SEGUIDORES_X_TABLEERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO_PK" ON "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO " ("CODIGO_USUARIO", "CODIGO_TABLERO ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_COMENTARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_COMENTARIO_PK" ON "DB_PINTEREST"."TBL_COMENTARIO " ("CODIGO_COMENTARIO ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_EMPRESA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_TIPO_EMPRESA_PK" ON "DB_PINTEREST"."TBL_TIPO_EMPRESA " ("CODIGO_TIPO_EMPRESA ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_NOTIFICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_TIPO_NOTIFICACION_PK" ON "DB_PINTEREST"."TBL_TIPO_NOTIFICACION " ("CODIGO_TIPO_NOTIFICACION ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DETUNCIA_X_TABLERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO_PK" ON "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" ("CODIGO_DENUNCIA ", "CODIGO_PINES ", "CODIGO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TABLERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_TABLERO_PK" ON "DB_PINTEREST"."TBL_TABLERO " ("CODIGO_TABLERO ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BANDEJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."BANDEJA_PK" ON "DB_PINTEREST"."TBL_CORREO" ("CODIGO_CORREO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DETUNCIA_X_COMENTARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO_PK" ON "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" ("CODIGO_USUARIO", "CODIGO_COMENTARIO ", "CODIGO_DENUNCIA ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_HISTORIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_HISTORIAL_PK" ON "DB_PINTEREST"."TBL_HISTORIAL" ("CODIGO_HISTORIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DETUNCIA_X_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO_PK" ON "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" ("CODIGO_USUARIO", "CODIGO_USUARIO_DENUNCIADO", "CODIGO_DENUNCIA ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CHAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_CHAT_PK" ON "DB_PINTEREST"."TBL_MENSAJE" ("CODIGO_MENSAJE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GENERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_GENERO_PK" ON "DB_PINTEREST"."TBL_GENERO " ("CODIGO_GENERO ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CATEGORIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_CATEGORIAS_PK" ON "DB_PINTEREST"."TBL_CATEGORIAS " ("CODIGO_CATEGORIA ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CORREO_X_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_CORREO_X_USUARIO_PK" ON "DB_PINTEREST"."TBL_CORREO_X_USUARIO" ("CODIGO_USUARIO", "CODIGO_USUARIO_DESTINO", "CODIGO_CORREO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_TABLERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_TIPO_TABLERO_PK" ON "DB_PINTEREST"."TBL_TIPO_TABLERO " ("CODIGO_TIPO_TABLERO ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CHAT_X_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_CHAT_X_USUARIO_PK" ON "DB_PINTEREST"."TBL_CHAT_X_USUARIO " ("CODIGO_USUARIO", "CODIGO_USUARIO_DESTINO", "CODIGO_MENSAJE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_EMPRESA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_EMPRESA_PK" ON "DB_PINTEREST"."TBL_EMPRESA" ("CODIGO_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_IDIOMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_IDIOMA_PK" ON "DB_PINTEREST"."TBL_IDIOMA" ("CODIGO_IDIOMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DETUNCIA_X_PIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_DETUNCIA_X_PIN_PK" ON "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" ("CODIGO_DENUNCIA ", "CODIGO_TABLERO ", "CODIGO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_REDES_SOCIALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_REDES_SOCIALES_PK" ON "DB_PINTEREST"."TBL_REDES_SOCIALES " ("CODIGO_RED_SOCIAL ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_BLOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_BLOG_PK" ON "DB_PINTEREST"."TBL_BLOG" ("CODIGO_PUBLICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_DENUNCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_TIPO_DENUNCIA_PK" ON "DB_PINTEREST"."TBL_TIPO_DENUNCIA " ("CODIGO_DENUNCIA ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PINES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_PINES_PK" ON "DB_PINTEREST"."TBL_PINES " ("CODIGO_PINES ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_LUGAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_LUGAR_PK" ON "DB_PINTEREST"."TBL_LUGAR " ("CODIGO_LUGAR ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_PINTEREST"."TBL_TIPO_USUARIO_PK" ON "DB_PINTEREST"."TBL_TIPO_USUARIO " ("CODIGO_TIPO_USUARIO ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_DETUNCIA_X_TABLERO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" ADD CONSTRAINT "TBL_DETUNCIA_X_PIN_PK" PRIMARY KEY ("CODIGO_DENUNCIA ", "CODIGO_TABLERO ", "CODIGO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" MODIFY ("CODIGO_DENUNCIA " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" MODIFY ("CODIGO_TABLERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_REDES_SOCIALES 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_REDES_SOCIALES " ADD CONSTRAINT "TBL_REDES_SOCIALES_PK" PRIMARY KEY ("CODIGO_RED_SOCIAL ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_REDES_SOCIALES " MODIFY ("CODIGO_RED_SOCIAL " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_GENERO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_GENERO " ADD CONSTRAINT "TBL_GENERO_PK" PRIMARY KEY ("CODIGO_GENERO ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_GENERO " MODIFY ("CODIGO_GENERO " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_NOTIFI_X_COMENTARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFI_X_COMENTARIO" MODIFY ("CODIGO_COMENTARIO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFI_X_COMENTARIO" MODIFY ("CODIGO_NOTIFICACIONES " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PERSONA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_PERSONA " ADD CONSTRAINT "TBL_PERSONA_PK" PRIMARY KEY ("CODIGO_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_PERSONA " MODIFY ("CODIGO_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_NOTIFICACIONES_X_PINES
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_PINES" MODIFY ("CODIGO_PINES " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_PINES" MODIFY ("CODIGO_NOTIFICACIONES " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TABLERO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO " ADD CONSTRAINT "TBL_TABLERO_PK" PRIMARY KEY ("CODIGO_TABLERO ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO " MODIFY ("CODIGO_TIPO_TABLERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO " MODIFY ("CODIGO_TABLERO " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_NOTIFICACION
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACION" ADD CONSTRAINT "TBL_NOTIFICACION_PK" PRIMARY KEY ("CODIGO_NOTIFICACIONES ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACION" MODIFY ("CODIGO_TIPO_NOTIFICACION " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACION" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACION" MODIFY ("CODIGO_NOTIFICACIONES " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CHAT_X_USUARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " ADD CONSTRAINT "TBL_CHAT_X_USUARIO_PK" PRIMARY KEY ("CODIGO_USUARIO", "CODIGO_USUARIO_DESTINO", "CODIGO_MENSAJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " MODIFY ("CODIGO_MENSAJE" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " MODIFY ("CODIGO_USUARIO_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_IDIOMA
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_IDIOMA" ADD CONSTRAINT "TBL_IDIOMA_PK" PRIMARY KEY ("CODIGO_IDIOMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_IDIOMA" MODIFY ("CODIGO_IDIOMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_REDES_X_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_REDES_X_USUARIO" MODIFY ("CODIGO_RED_SOCIAL " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_REDES_X_USUARIO" MODIFY ("CODIGO_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_SEGUIDORES_X_CATEGORIA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_CATEGORIA " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_CATEGORIA " MODIFY ("CODIGO_CATEGORIA " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CORREO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_CORREO" ADD CONSTRAINT "BANDEJA_PK" PRIMARY KEY ("CODIGO_CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CORREO" MODIFY ("CODIGO_CORREO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_EMPRESA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_EMPRESA " ADD CONSTRAINT "TBL_TIPO_EMPRESA_PK" PRIMARY KEY ("CODIGO_TIPO_EMPRESA ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_EMPRESA " MODIFY ("CODIGO_TIPO_EMPRESA " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MENSAJE
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_MENSAJE" ADD CONSTRAINT "TBL_CHAT_PK" PRIMARY KEY ("CODIGO_MENSAJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_MENSAJE" MODIFY ("CODIGO_MENSAJE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_HISTORIAL
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_HISTORIAL" ADD CONSTRAINT "TBL_HISTORIAL_PK" PRIMARY KEY ("CODIGO_HISTORIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_HISTORIAL" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_HISTORIAL" MODIFY ("CODIGO_HISTORIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DETUNCIA_X_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" ADD CONSTRAINT "TBL_DETUNCIA_X_USUARIO_PK" PRIMARY KEY ("CODIGO_USUARIO", "CODIGO_USUARIO_DENUNCIADO", "CODIGO_DENUNCIA ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" MODIFY ("CODIGO_DENUNCIA " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" MODIFY ("CODIGO_USUARIO_DENUNCIADO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_COMENTARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_COMENTARIO " ADD CONSTRAINT "TBL_COMENTARIO_PK" PRIMARY KEY ("CODIGO_COMENTARIO ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_COMENTARIO " MODIFY ("CODIGO_PINES " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_COMENTARIO " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_COMENTARIO " MODIFY ("CODIGO_COMENTARIO " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_NOTIFICACION 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_NOTIFICACION " ADD CONSTRAINT "TBL_TIPO_NOTIFICACION_PK" PRIMARY KEY ("CODIGO_TIPO_NOTIFICACION ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_NOTIFICACION " MODIFY ("CODIGO_TIPO_NOTIFICACION " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_EMPRESA" ADD CONSTRAINT "TBL_EMPRESA_PK" PRIMARY KEY ("CODIGO_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_EMPRESA" MODIFY ("CODIGO_TIPO_EMPRESA " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_EMPRESA" MODIFY ("CODIGO_EMPRESA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TABLERO_X_CATEGORIA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_CATEGORIA " MODIFY ("CODIGO_TABLERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_CATEGORIA " MODIFY ("CODIGO_CATEGORIA " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BLOG
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_BLOG" ADD CONSTRAINT "TBL_BLOG_PK" PRIMARY KEY ("CODIGO_PUBLICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_BLOG" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_BLOG" MODIFY ("CODIGO_PUBLICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DETUNCIA_X_PIN
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" ADD CONSTRAINT "TBL_DETUNCIA_X_TABLERO_PK" PRIMARY KEY ("CODIGO_DENUNCIA ", "CODIGO_PINES ", "CODIGO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" MODIFY ("CODIGO_DENUNCIA " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" MODIFY ("CODIGO_PINES " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_NOTIFICACIONES_X_TABLERO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_TABLERO" MODIFY ("CODIGO_TABLERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_TABLERO" MODIFY ("CODIGO_NOTIFICACIONES " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_LUGAR 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_LUGAR " ADD CONSTRAINT "TBL_LUGAR_PK" PRIMARY KEY ("CODIGO_LUGAR ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_LUGAR " MODIFY ("CODIGO_LUGAR " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CORREO_X_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" ADD CONSTRAINT "TBL_CORREO_X_USUARIO_PK" PRIMARY KEY ("CODIGO_USUARIO", "CODIGO_USUARIO_DESTINO", "CODIGO_CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" MODIFY ("CODIGO_CORREO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" MODIFY ("CODIGO_USUARIO_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_FOTOS
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_FOTOS" ADD CONSTRAINT "TBL_FOTOS_PK" PRIMARY KEY ("CODIGO_FOTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_FOTOS" MODIFY ("CODIGO_FOTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_USUARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_USUARIO " ADD CONSTRAINT "TBL_TIPO_USUARIO_PK" PRIMARY KEY ("CODIGO_TIPO_USUARIO ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_USUARIO " MODIFY ("CODIGO_TIPO_USUARIO " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_SEGUIDORES_X_USUARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_USUARIO " MODIFY ("CODIGO_SEGUIDOR" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_USUARIO " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_SEGUIDORES_X_TABLEERO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO " ADD CONSTRAINT "TBL_SEGUIDORES_X_TABLEERO_PK" PRIMARY KEY ("CODIGO_USUARIO", "CODIGO_TABLERO ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO " MODIFY ("CODIGO_TABLERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_DENUNCIA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_DENUNCIA " ADD CONSTRAINT "TBL_TIPO_DENUNCIA_PK" PRIMARY KEY ("CODIGO_DENUNCIA ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_DENUNCIA " MODIFY ("CODIGO_DENUNCIA " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PINES 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_PINES " ADD CONSTRAINT "TBL_PINES_PK" PRIMARY KEY ("CODIGO_PINES ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_PINES " MODIFY ("CODIGO_FOTO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_PINES " MODIFY ("CODIGO_TABLERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_PINES " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_PINES " MODIFY ("CODIGO_PINES " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORIAS 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_CATEGORIAS " ADD CONSTRAINT "TBL_CATEGORIAS_PK" PRIMARY KEY ("CODIGO_CATEGORIA ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CATEGORIAS " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_CATEGORIAS " MODIFY ("CODIGO_CATEGORIA " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DETUNCIA_X_COMENTARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" ADD CONSTRAINT "TBL_DETUNCIA_X_COMENTARIO_PK" PRIMARY KEY ("CODIGO_USUARIO", "CODIGO_COMENTARIO ", "CODIGO_DENUNCIA ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" MODIFY ("CODIGO_DENUNCIA " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" MODIFY ("CODIGO_COMENTARIO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" ADD CONSTRAINT "TBL_USUARIO_PK" PRIMARY KEY ("CODIGO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" MODIFY ("CODIGO_IDIOMA" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" MODIFY ("CODIGO_FOTO" NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" MODIFY ("CODIGO_GENERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" MODIFY ("CODIGO_TIPO_USUARIO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" MODIFY ("CODIGO_LUGAR " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_TABLERO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_TABLERO " ADD CONSTRAINT "TBL_TIPO_TABLERO_PK" PRIMARY KEY ("CODIGO_TIPO_TABLERO ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TIPO_TABLERO " MODIFY ("CODIGO_TIPO_TABLERO " NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TABLERO_X_USUARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_USUARIO " ADD CONSTRAINT "TBL_TABLERO_X_USUARIO_PK" PRIMARY KEY ("CODIGO_USUARIO", "CODIGO_TABLERO ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_USUARIO " MODIFY ("CODIGO_TABLERO " NOT NULL ENABLE);
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_USUARIO " MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_BLOG
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_BLOG" ADD CONSTRAINT "TBL_BLO_TBL_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CATEGORIAS 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_CATEGORIAS " ADD CONSTRAINT " TBL_CAT_FK" FOREIGN KEY ("CODIGO_CATEGORIA_PADRE")
	  REFERENCES "DB_PINTEREST"."TBL_CATEGORIAS " ("CODIGO_CATEGORIA ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CATEGORIAS " ADD CONSTRAINT "TBL_CAT _TBL_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CHAT_X_USUARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " ADD CONSTRAINT "TBL_CHA_X_USU _TBL_CHA" FOREIGN KEY ("CODIGO_MENSAJE")
	  REFERENCES "DB_PINTEREST"."TBL_MENSAJE" ("CODIGO_MENSAJE") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " ADD CONSTRAINT "TBL_CHA_X_USU_TBL_USU" FOREIGN KEY ("CODIGO_USUARIO_DESTINO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CHAT_X_USUARIO " ADD CONSTRAINT "TBL_CHA_X_USU_TBL_USUV2" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_COMENTARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_COMENTARIO " ADD CONSTRAINT "TBL_COM _TBL_PIN _FK" FOREIGN KEY ("CODIGO_PINES ")
	  REFERENCES "DB_PINTEREST"."TBL_PINES " ("CODIGO_PINES ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_COMENTARIO " ADD CONSTRAINT "TBL_COM _TBL_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CORREO_X_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" ADD CONSTRAINT "TBL_COR_X_USU_TBL_COR" FOREIGN KEY ("CODIGO_CORREO")
	  REFERENCES "DB_PINTEREST"."TBL_CORREO" ("CODIGO_CORREO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" ADD CONSTRAINT "TBL_COR_X_USU_TBL_USU" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_CORREO_X_USUARIO" ADD CONSTRAINT "TBL_COR_X_USU_USU" FOREIGN KEY ("CODIGO_USUARIO_DESTINO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETUNCIA_X_COMENTARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" ADD CONSTRAINT "TBL_DEN_X_COM_TBL_USU" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" ADD CONSTRAINT "TBL_DEN_X_COM_TIP_DEN" FOREIGN KEY ("CODIGO_DENUNCIA ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_DENUNCIA " ("CODIGO_DENUNCIA ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_COMENTARIO" ADD CONSTRAINT "TBL_DET_X_COM_TBL_COM" FOREIGN KEY ("CODIGO_COMENTARIO ")
	  REFERENCES "DB_PINTEREST"."TBL_COMENTARIO " ("CODIGO_COMENTARIO ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETUNCIA_X_PIN
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" ADD CONSTRAINT "TBL_DEN_X_TAB_PIN" FOREIGN KEY ("CODIGO_PINES ")
	  REFERENCES "DB_PINTEREST"."TBL_PINES " ("CODIGO_PINES ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" ADD CONSTRAINT "TBL_DEN_X_TAB_TIP_DEN" FOREIGN KEY ("CODIGO_DENUNCIA ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_DENUNCIA " ("CODIGO_DENUNCIA ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_PIN" ADD CONSTRAINT "TBL_DEN_X_USU" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETUNCIA_X_TABLERO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" ADD CONSTRAINT "TBL_DEN_X_PIN_TIP_DEN" FOREIGN KEY ("CODIGO_DENUNCIA ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_DENUNCIA " ("CODIGO_DENUNCIA ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" ADD CONSTRAINT "TBL_DEN_X_PIN_USU" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_TABLERO" ADD CONSTRAINT "TBL_DE_X_PIN_TBL_TAB _FK" FOREIGN KEY ("CODIGO_TABLERO ")
	  REFERENCES "DB_PINTEREST"."TBL_TABLERO " ("CODIGO_TABLERO ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETUNCIA_X_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" ADD CONSTRAINT "TBL_DEN_X_USU_TBL_USU" FOREIGN KEY ("CODIGO_USUARIO_DENUNCIADO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" ADD CONSTRAINT "TBL_DEN_X_USU_TIP_DEN" FOREIGN KEY ("CODIGO_DENUNCIA ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_DENUNCIA " ("CODIGO_DENUNCIA ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_DETUNCIA_X_USUARIO" ADD CONSTRAINT "TBL_DEN_X_USU_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_EMPRESA" ADD CONSTRAINT "TBL_EMP_TBL_TIP_EMP" FOREIGN KEY ("CODIGO_TIPO_EMPRESA ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_EMPRESA " ("CODIGO_TIPO_EMPRESA ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_EMPRESA" ADD CONSTRAINT "TBL_EMP_TBL_USU" FOREIGN KEY ("CODIGO_EMPRESA")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_HISTORIAL
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_HISTORIAL" ADD CONSTRAINT "TBL_HIS_TBL_USU" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_LUGAR 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_LUGAR " ADD CONSTRAINT "TBL_LUG_LUG" FOREIGN KEY ("CODIGO_LUGAR_PADRE")
	  REFERENCES "DB_PINTEREST"."TBL_LUGAR " ("CODIGO_LUGAR ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_NOTIFICACION
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACION" ADD CONSTRAINT "TBL_NOT_TBL_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACION" ADD CONSTRAINT "TBL_NOT_TIP_NOT" FOREIGN KEY ("CODIGO_TIPO_NOTIFICACION ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_NOTIFICACION " ("CODIGO_TIPO_NOTIFICACION ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_NOTIFICACIONES_X_PINES
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_PINES" ADD CONSTRAINT "TBL_NOT_PIN _FK" FOREIGN KEY ("CODIGO_PINES ")
	  REFERENCES "DB_PINTEREST"."TBL_PINES " ("CODIGO_PINES ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_PINES" ADD CONSTRAINT "TBL_NOT_PIN_TBL_NOT_FK" FOREIGN KEY ("CODIGO_NOTIFICACIONES ")
	  REFERENCES "DB_PINTEREST"."TBL_NOTIFICACION" ("CODIGO_NOTIFICACIONES ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_NOTIFICACIONES_X_TABLERO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_TABLERO" ADD CONSTRAINT "TBL_NOTL_TAB _FK" FOREIGN KEY ("CODIGO_TABLERO ")
	  REFERENCES "DB_PINTEREST"."TBL_TABLERO " ("CODIGO_TABLERO ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFICACIONES_X_TABLERO" ADD CONSTRAINT "TBL_NOT_X_TAB_NOT_FK" FOREIGN KEY ("CODIGO_NOTIFICACIONES ")
	  REFERENCES "DB_PINTEREST"."TBL_NOTIFICACION" ("CODIGO_NOTIFICACIONES ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_NOTIFI_X_COMENTARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFI_X_COMENTARIO" ADD CONSTRAINT "TBL_NOT_COM_TBL_COM" FOREIGN KEY ("CODIGO_COMENTARIO ")
	  REFERENCES "DB_PINTEREST"."TBL_COMENTARIO " ("CODIGO_COMENTARIO ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_NOTIFI_X_COMENTARIO" ADD CONSTRAINT "TBL_NOT_X_COM_NOT_FK" FOREIGN KEY ("CODIGO_NOTIFICACIONES ")
	  REFERENCES "DB_PINTEREST"."TBL_NOTIFICACION" ("CODIGO_NOTIFICACIONES ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PERSONA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_PERSONA " ADD CONSTRAINT "TBL_PER _TBL_USU" FOREIGN KEY ("CODIGO_PERSONA")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PINES 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_PINES " ADD CONSTRAINT "TBL_PIN _TBL_FOT_FK" FOREIGN KEY ("CODIGO_FOTO")
	  REFERENCES "DB_PINTEREST"."TBL_FOTOS" ("CODIGO_FOTO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_PINES " ADD CONSTRAINT "TBL_PIN _TBL_TAB _FK" FOREIGN KEY ("CODIGO_TABLERO ")
	  REFERENCES "DB_PINTEREST"."TBL_TABLERO " ("CODIGO_TABLERO ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_PINES " ADD CONSTRAINT "TBL_PIN _TBL_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_REDES_X_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_REDES_X_USUARIO" ADD CONSTRAINT "TBL_RED_X_USU_PER_FK" FOREIGN KEY ("CODIGO_PERSONA")
	  REFERENCES "DB_PINTEREST"."TBL_PERSONA " ("CODIGO_PERSONA") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_REDES_X_USUARIO" ADD CONSTRAINT "TBL_RED_X_USU_SOC" FOREIGN KEY ("CODIGO_RED_SOCIAL ")
	  REFERENCES "DB_PINTEREST"."TBL_REDES_SOCIALES " ("CODIGO_RED_SOCIAL ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SEGUIDORES_X_CATEGORIA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_CATEGORIA " ADD CONSTRAINT "TBL_SEG_CAT_TBL_USU" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_CATEGORIA " ADD CONSTRAINT "TBL_SEG_X_CAT_CAT" FOREIGN KEY ("CODIGO_CATEGORIA ")
	  REFERENCES "DB_PINTEREST"."TBL_CATEGORIAS " ("CODIGO_CATEGORIA ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SEGUIDORES_X_TABLEERO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO " ADD CONSTRAINT "TBL_SEG_TAB _FK" FOREIGN KEY ("CODIGO_TABLERO ")
	  REFERENCES "DB_PINTEREST"."TBL_TABLERO " ("CODIGO_TABLERO ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_TABLEERO " ADD CONSTRAINT "TBL_SEG_X_TAB_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SEGUIDORES_X_USUARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_USUARIO " ADD CONSTRAINT "TBL_SEG_USU_TBL_USU" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_SEGUIDORES_X_USUARIO " ADD CONSTRAINT "TBL_SEG_X_USU_USU" FOREIGN KEY ("CODIGO_SEGUIDOR")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_TABLERO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO " ADD CONSTRAINT "TBL_TAB_TIP_TAB _FK" FOREIGN KEY ("CODIGO_TIPO_TABLERO ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_TABLERO " ("CODIGO_TIPO_TABLERO ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO " ADD CONSTRAINT "TBL_TAB_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_TABLERO_X_CATEGORIA 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_CATEGORIA " ADD CONSTRAINT "TBL_TAB_X_CAT" FOREIGN KEY ("CODIGO_CATEGORIA ")
	  REFERENCES "DB_PINTEREST"."TBL_CATEGORIAS " ("CODIGO_CATEGORIA ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_CATEGORIA " ADD CONSTRAINT "TBL_TAB_X_CAT_TAB _FK" FOREIGN KEY ("CODIGO_TABLERO ")
	  REFERENCES "DB_PINTEREST"."TBL_TABLERO " ("CODIGO_TABLERO ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_TABLERO_X_USUARIO 
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_USUARIO " ADD CONSTRAINT "TBL_TAB_X_USU_USU_FK" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "DB_PINTEREST"."TBL_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_TABLERO_X_USUARIO " ADD CONSTRAINT "TBL_USU_TAB _FK" FOREIGN KEY ("CODIGO_TABLERO ")
	  REFERENCES "DB_PINTEREST"."TBL_TABLERO " ("CODIGO_TABLERO ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" ADD CONSTRAINT "TBL_USU_FOT_FK" FOREIGN KEY ("CODIGO_FOTO")
	  REFERENCES "DB_PINTEREST"."TBL_FOTOS" ("CODIGO_FOTO") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" ADD CONSTRAINT "TBL_USU_GEN _FK" FOREIGN KEY ("CODIGO_GENERO ")
	  REFERENCES "DB_PINTEREST"."TBL_GENERO " ("CODIGO_GENERO ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" ADD CONSTRAINT "TBL_USU_IDI_FK" FOREIGN KEY ("CODIGO_IDIOMA")
	  REFERENCES "DB_PINTEREST"."TBL_IDIOMA" ("CODIGO_IDIOMA") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" ADD CONSTRAINT "TBL_USU_LUG_FK" FOREIGN KEY ("CODIGO_LUGAR ")
	  REFERENCES "DB_PINTEREST"."TBL_LUGAR " ("CODIGO_LUGAR ") ENABLE;
  ALTER TABLE "DB_PINTEREST"."TBL_USUARIO" ADD CONSTRAINT "TBL_USU_TIP_USU _FK" FOREIGN KEY ("CODIGO_TIPO_USUARIO ")
	  REFERENCES "DB_PINTEREST"."TBL_TIPO_USUARIO " ("CODIGO_TIPO_USUARIO ") ENABLE;
